language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_install:
  - yarn global add http-server
script:
  - yarn test
  - yarn cypress:ci
after_script: "cat ./coverage/lcov.info | coveralls"
